fullname: Pipeline Testing
shortname: piptest
branch: main
organization: motrellin

action: true

community: false
coqdoc: true
submodule: true #At least for coqdocjs
synopsis: Playing around with Github pipelines
description: |
  Playing

authors:
  - name: Max Ole Elliger
    initial: true
    email: ole.elliger@fau.de
maintainers:
  - name: Max Ole Elliger
    nickname: motrellin

supported_coq_versions:
  text: Developed for "9.0"
  opam: '{ >= "9.0" }'

make_target: all

tested_rocq_opam_versions:
  - version: "9.0"
